server:
  port: 8006
spring:
  application:
    name: PAYMENT-SERVICE
  h2:
    console:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

